Updated workflow, added Audio submodule

diff --git a/.github/workflows/LinuxTests.yml b/.github/workflows/LinuxTests.yml
--- a/.github/workflows/LinuxTests.yml
+++ b/.github/workflows/LinuxTests.yml
@@ -45,7 +45,16 @@ jobs:
       env:
         CC:  gcc-10
         CXX: g++-10
-      run: echo "::set-output name=Coverage::$((make run_core_coverage && echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' ')) || echo "Failure")"
+      continue-on-error: true
+      run: |
+        make run_core_coverage
+        if [ $? = 0 ]; then
+          echo "::set-output name=Coverage::$(echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' '))"
+          echo "::set-output name=Color::green"
+        else
+          echo "::set-output name=Coverage::Failure"
+          echo "::set-output name=Color::red"
+        fi
 
     - name: Upload Core coverage
       uses: RubbaBoy/BYOB@v1.2.0
@@ -64,7 +73,16 @@ jobs:
       env:
         CC:  gcc-10
         CXX: g++-10
-      run: echo "::set-output name=Coverage::$((make run_meta_coverage && echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' ')) || echo "Failure")"
+      continue-on-error: true
+      run: |
+        make run_meta_coverage
+        if [ $? = 0 ]; then
+          echo "::set-output name=Coverage::$(echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' '))"
+          echo "::set-output name=Color::green"
+        else
+          echo "::set-output name=Coverage::Failure"
+          echo "::set-output name=Color::red"
+        fi
 
     - name: Upload Meta coverage
       uses: RubbaBoy/BYOB@v1.2.0
@@ -83,7 +101,16 @@ jobs:
       env:
         CC:  gcc-10
         CXX: g++-10
-      run: echo "::set-output name=Coverage::$((make run_flow_coverage && echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' ')) || echo "Failure")"
+      continue-on-error: true
+      run: |
+        make run_flow_coverage
+        if [ $? = 0 ]; then
+          echo "::set-output name=Coverage::$(echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' '))"
+          echo "::set-output name=Color::green"
+        else
+          echo "::set-output name=Coverage::Failure"
+          echo "::set-output name=Color::red"
+        fi
 
     - name: Upload Flow coverage
       uses: RubbaBoy/BYOB@v1.2.0
@@ -102,7 +129,16 @@ jobs:
       env:
         CC:  gcc-10
         CXX: g++-10
-      run: echo "::set-output name=Coverage::$((make run_graphics_coverage && echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' ')) || echo "Failure")"
+      continue-on-error: true
+      run: |
+        make run_graphics_coverage
+        if [ $? = 0 ]; then
+          echo "::set-output name=Coverage::$(echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' '))"
+          echo "::set-output name=Color::green"
+        else
+          echo "::set-output name=Coverage::Failure"
+          echo "::set-output name=Color::red"
+        fi
 
     - name: Upload Graphics coverage
       uses: RubbaBoy/BYOB@v1.2.0
@@ -121,7 +157,16 @@ jobs:
       env:
         CC:  gcc-10
         CXX: g++-10
-      run: echo "::set-output name=Coverage::$((make run_object_coverage && echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' ')) || echo "Failure")"
+      continue-on-error: true
+      run: |
+        make run_object_coverage
+        if [ $? = 0 ]; then
+          echo "::set-output name=Coverage::$(echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' '))"
+          echo "::set-output name=Color::green"
+        else
+          echo "::set-output name=Coverage::Failure"
+          echo "::set-output name=Color::red"
+        fi
 
     - name: Upload Objects coverage
       uses: RubbaBoy/BYOB@v1.2.0
@@ -140,7 +185,16 @@ jobs:
       env:
         CC:  gcc-10
         CXX: g++-10
-      run: echo "::set-output name=Coverage::$((make run_ecs_coverage && echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' ')) || echo "Failure")"
+      continue-on-error: true
+      run: |
+        make run_ecs_coverage
+        if [ $? = 0 ]; then
+          echo "::set-output name=Coverage::$(echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' '))"
+          echo "::set-output name=Color::green"
+        else
+          echo "::set-output name=Coverage::Failure"
+          echo "::set-output name=Color::red"
+        fi
 
     - name: Upload ECS coverage
       uses: RubbaBoy/BYOB@v1.2.0
@@ -159,7 +213,16 @@ jobs:
       env:
         CC:  gcc-10
         CXX: g++-10
-      run: echo "::set-output name=Coverage::$((make run_ui_coverage && echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' ')) || echo "Failure")"
+      continue-on-error: true
+      run: |
+        make run_ui_coverage
+        if [ $? = 0 ]; then
+          echo "::set-output name=Coverage::$(echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' '))"
+          echo "::set-output name=Color::green"
+        else
+          echo "::set-output name=Coverage::Failure"
+          echo "::set-output name=Color::red"
+        fi
 
     - name: Upload UI coverage
       uses: RubbaBoy/BYOB@v1.2.0
@@ -178,7 +241,16 @@ jobs:
       env:
         CC:  gcc-10
         CXX: g++-10
-      run: echo "::set-output name=Coverage::$((make run_widgets_coverage && echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' ')) || echo "Failure")"
+      continue-on-error: true
+      run: |
+        make run_widgets_coverage
+        if [ $? = 0 ]; then
+          echo "::set-output name=Coverage::$(echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' '))"
+          echo "::set-output name=Color::green"
+        else
+          echo "::set-output name=Coverage::Failure"
+          echo "::set-output name=Color::red"
+        fi
 
     - name: Upload Widgets coverage
       uses: RubbaBoy/BYOB@v1.2.0
@@ -197,7 +269,16 @@ jobs:
       env:
         CC:  gcc-10
         CXX: g++-10
-      run: echo "::set-output name=Coverage::$((make run_voxel_coverage && echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' ')) || echo "Failure")"
+      continue-on-error: true
+      run: |
+        make run_voxel_coverage
+        if [ $? = 0 ]; then
+          echo "::set-output name=Coverage::$(echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' '))"
+          echo "::set-output name=Color::green"
+        else
+          echo "::set-output name=Coverage::Failure"
+          echo "::set-output name=Color::red"
+        fi
 
     - name: Upload Voxel coverage
       uses: RubbaBoy/BYOB@v1.2.0
