Update

diff --git a/.github/workflows/LinuxTests.yml b/.github/workflows/LinuxTests.yml
--- a/.github/workflows/LinuxTests.yml
+++ b/.github/workflows/LinuxTests.yml
@@ -60,9 +60,9 @@ jobs:
       uses: RubbaBoy/BYOB@v1.2.0
       with:
         NAME: CoreCoverage
-        LABEL: 'Coverage'
+        LABEL: 'Linux Tests Coverage'
         STATUS: ${{ steps.CoreTests.outputs.Coverage }}
-        COLOR: blue
+        COLOR: ${{ steps.CoreTests.outputs.Color }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
     # Meta
@@ -88,9 +88,9 @@ jobs:
       uses: RubbaBoy/BYOB@v1.2.0
       with:
         NAME: MetaCoverage
-        LABEL: 'Coverage'
+        LABEL: 'Linux Tests Coverage'
         STATUS: ${{ steps.MetaTests.outputs.Coverage }}
-        COLOR: blue
+        COLOR: ${{ steps.MetaTests.outputs.Color }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
     # Flow
@@ -116,9 +116,9 @@ jobs:
       uses: RubbaBoy/BYOB@v1.2.0
       with:
         NAME: FlowCoverage
-        LABEL: 'Coverage'
+        LABEL: 'Linux Tests Coverage'
         STATUS: ${{ steps.FlowTests.outputs.Coverage }}
-        COLOR: blue
+        COLOR: ${{ steps.FlowTests.outputs.Color }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
     # Graphics
@@ -144,14 +144,14 @@ jobs:
       uses: RubbaBoy/BYOB@v1.2.0
       with:
         NAME: GraphicsCoverage
-        LABEL: 'Coverage'
+        LABEL: 'Linux Tests Coverage'
         STATUS: ${{ steps.GraphicsTests.outputs.Coverage }}
-        COLOR: blue
+        COLOR: ${{ steps.GraphicsTests.outputs.Color }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
     # Object
-    - name: Run Objects tests
-      id: ObjectsTests
+    - name: Run Object tests
+      id: ObjectTests
       working-directory: ${{github.workspace}}
       shell: bash
       env:
@@ -168,13 +168,42 @@ jobs:
           echo "::set-output name=Color::red"
         fi
 
-    - name: Upload Objects coverage
+    - name: Upload Object coverage
       uses: RubbaBoy/BYOB@v1.2.0
       with:
-        NAME: ObjectsCoverage
-        LABEL: 'Coverage'
-        STATUS: ${{ steps.ObjectsTests.outputs.Coverage }}
-        COLOR: blue
+        NAME: ObjectCoverage
+        LABEL: 'Linux Tests Coverage'
+        STATUS: ${{ steps.ObjectTests.outputs.Coverage }}
+        COLOR: ${{ steps.ObjectTests.outputs.Color }}
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+
+    # Interpreter
+    - name: Run Interpreter tests
+      id: InterpreterTests
+      working-directory: ${{github.workspace}}
+      shell: bash
+      env:
+        CC:  gcc-10
+        CXX: g++-10
+      continue-on-error: true
+      run: |
+        make run_interpreter_coverage
+        if [ $? = 0 ]; then
+          echo "::set-output name=Coverage::$(echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' '))"
+          echo "::set-output name=Color::green"
+        else
+          echo "::set-output name=Coverage::Failure"
+          echo "::set-output name=Color::red"
+        fi
+
+    - name: Upload Interpreter coverage
+      uses: RubbaBoy/BYOB@v1.2.0
+      with:
+        NAME: InterpreterCoverage
+        LABEL: 'Linux Tests Coverage'
+        STATUS: ${{ steps.InterpreterTests.outputs.Coverage }}
+        COLOR: ${{ steps.InterpreterTests.outputs.Color }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
     # ECS
@@ -200,9 +229,9 @@ jobs:
       uses: RubbaBoy/BYOB@v1.2.0
       with:
         NAME: ECSCoverage
-        LABEL: 'Coverage'
+        LABEL: 'Linux Tests Coverage'
         STATUS: ${{ steps.ECSTests.outputs.Coverage }}
-        COLOR: blue
+        COLOR: ${{ steps.ECSTests.outputs.Color }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
     # UI
@@ -228,9 +257,9 @@ jobs:
       uses: RubbaBoy/BYOB@v1.2.0
       with:
         NAME: UICoverage
-        LABEL: 'Coverage'
+        LABEL: 'Linux Tests Coverage'
         STATUS: ${{ steps.UITests.outputs.Coverage }}
-        COLOR: blue
+        COLOR: ${{ steps.UITests.outputs.Color }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
     # Widgets
@@ -256,9 +285,9 @@ jobs:
       uses: RubbaBoy/BYOB@v1.2.0
       with:
         NAME: WidgetsCoverage
-        LABEL: 'Coverage'
+        LABEL: 'Linux Tests Coverage'
         STATUS: ${{ steps.WidgetsTests.outputs.Coverage }}
-        COLOR: blue
+        COLOR: ${{ steps.WidgetsTests.outputs.Color }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
     # Voxel
@@ -284,7 +313,35 @@ jobs:
       uses: RubbaBoy/BYOB@v1.2.0
       with:
         NAME: VoxelCoverage
-        LABEL: 'Coverage'
+        LABEL: 'Linux Tests Coverage'
         STATUS: ${{ steps.VoxelTests.outputs.Coverage }}
-        COLOR:  blue
+        COLOR: ${{ steps.VoxelTests.outputs.Color }}
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+    # App
+    - name: Run App tests
+      id: AppTests
+      working-directory: ${{github.workspace}}
+      shell: bash
+      env:
+        CC:  gcc-10
+        CXX: g++-10
+      continue-on-error: true
+      run: |
+        make run_app_coverage
+        if [ $? = 0 ]; then
+          echo "::set-output name=Coverage::$(echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' '))"
+          echo "::set-output name=Color::green"
+        else
+          echo "::set-output name=Coverage::Failure"
+          echo "::set-output name=Color::red"
+        fi
+
+    - name: Upload App coverage
+      uses: RubbaBoy/BYOB@v1.2.0
+      with:
+        NAME: AppCoverage
+        LABEL: 'Linux Tests Coverage'
+        STATUS: ${{ steps.AppTests.outputs.Coverage }}
+        COLOR: ${{ steps.AppTests.outputs.Color }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
