Updated workflow

diff --git a/.github/workflows/LinuxTests.yml b/.github/workflows/LinuxTests.yml
--- a/.github/workflows/LinuxTests.yml
+++ b/.github/workflows/LinuxTests.yml
@@ -29,13 +29,13 @@ jobs:
     - name: Install Vulkan
       run: sudo apt-get install -y libvulkan-dev libvulkan1 mesa-vulkan-drivers vulkan-tools vulkan-utils vulkan-validationlayers vulkan-validationlayers-dev
 
-    # - name: Build
-    #   working-directory: ${{github.workspace}}
-    #   shell: bash
-    #   env:
-    #     CC:  gcc-10
-    #     CXX: g++-10
-    #   run: make coverage
+    - name: Build
+      working-directory: ${{github.workspace}}
+      shell: bash
+      env:
+        CC:  gcc-10
+        CXX: g++-10
+      run: make coverage
 
     # Core
     - name: Run Core tests
@@ -45,9 +45,7 @@ jobs:
       env:
         CC:  gcc-10
         CXX: g++-10
-      run: |
-        make run_core_coverage
-        echo "::set-output name=Coverage::$(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' ')"
+      run: echo "::set-output name=Coverage::$((make run_core_coverage && echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' ')) || echo "Failure")"
 
     - name: Upload Core coverage
       uses: RubbaBoy/BYOB@v1.2.0
@@ -59,129 +57,153 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
     # Meta
-    # - name: Run Meta tests
-    #   working-directory: ${{github.workspace}}
-    #   shell: bash
-    #   env:
-    #     CC:  gcc-10
-    #     CXX: g++-10
-    #   run: make run_meta_coverage
+    - name: Run Meta tests
+      id: MetaTests
+      working-directory: ${{github.workspace}}
+      shell: bash
+      env:
+        CC:  gcc-10
+        CXX: g++-10
+      run: echo "::set-output name=Coverage::$((make run_meta_coverage && echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' ')) || echo "Failure")"
 
-    # - name: Upload Meta coverage
-    #   working-directory: ${{github.workspace}}
-    #   shell: bash
-    #   env:
-    #     CODECOV_TOKEN: b3b12058-0308-4524-badb-7acd6efdcb89
-    #   run: bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Error while collecting coverage reports"
+    - name: Upload Meta coverage
+      uses: RubbaBoy/BYOB@v1.2.0
+      with:
+        NAME: MetaCoverage
+        LABEL: 'Coverage'
+        STATUS: ${{ steps.MetaTests.outputs.Coverage }}
+        COLOR: blue
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
     # Flow
-    # - name: Run Flow tests
-    #   working-directory: ${{github.workspace}}
-    #   shell: bash
-    #   env:
-    #     CC:  gcc-10
-    #     CXX: g++-10
-    #   run: make run_flow_coverage
+    - name: Run Flow tests
+      id: FlowTests
+      working-directory: ${{github.workspace}}
+      shell: bash
+      env:
+        CC:  gcc-10
+        CXX: g++-10
+      run: echo "::set-output name=Coverage::$((make run_flow_coverage && echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' ')) || echo "Failure")"
 
-    # - name: Upload Flow coverage
-    #   working-directory: ${{github.workspace}}
-    #   shell: bash
-    #   env:
-    #     CODECOV_TOKEN: 9a541471-c473-4a50-bf35-e14cdde37f17
-    #   run: bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Error while collecting coverage reports"
+    - name: Upload Flow coverage
+      uses: RubbaBoy/BYOB@v1.2.0
+      with:
+        NAME: FlowCoverage
+        LABEL: 'Coverage'
+        STATUS: ${{ steps.FlowTests.outputs.Coverage }}
+        COLOR: blue
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
     # Graphics
-    # - name: Run Graphics tests
-    #   working-directory: ${{github.workspace}}
-    #   shell: bash
-    #   env:
-    #     CC:  gcc-10
-    #     CXX: g++-10
-    #   run: make run_graphics_coverage
+    - name: Run Graphics tests
+      id: GraphicsTests
+      working-directory: ${{github.workspace}}
+      shell: bash
+      env:
+        CC:  gcc-10
+        CXX: g++-10
+      run: echo "::set-output name=Coverage::$((make run_graphics_coverage && echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' ')) || echo "Failure")"
 
-    # - name: Upload Graphics coverage
-    #   working-directory: ${{github.workspace}}
-    #   shell: bash
-    #   env:
-    #     CODECOV_TOKEN: d690b2c2-63af-460f-9894-0aba1cbb04c2
-    #   run: bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Error while collecting coverage reports"
+    - name: Upload Graphics coverage
+      uses: RubbaBoy/BYOB@v1.2.0
+      with:
+        NAME: GraphicsCoverage
+        LABEL: 'Coverage'
+        STATUS: ${{ steps.GraphicsTests.outputs.Coverage }}
+        COLOR: blue
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
     # Object
-    # - name: Run Object tests
-    #   working-directory: ${{github.workspace}}
-    #   shell: bash
-    #   env:
-    #     CC:  gcc-10
-    #     CXX: g++-10
-    #   run: make run_object_coverage
+    - name: Run Objects tests
+      id: ObjectsTests
+      working-directory: ${{github.workspace}}
+      shell: bash
+      env:
+        CC:  gcc-10
+        CXX: g++-10
+      run: echo "::set-output name=Coverage::$((make run_object_coverage && echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' ')) || echo "Failure")"
 
-    # - name: Upload Object coverage
-    #   working-directory: ${{github.workspace}}
-    #   shell: bash
-    #   env:
-    #     CODECOV_TOKEN: 3b9c6003-3a03-4d67-94ef-3f5c83b7fe4d
-    #   run: bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Error while collecting coverage reports"
+    - name: Upload Objects coverage
+      uses: RubbaBoy/BYOB@v1.2.0
+      with:
+        NAME: ObjectsCoverage
+        LABEL: 'Coverage'
+        STATUS: ${{ steps.ObjectsTests.outputs.Coverage }}
+        COLOR: blue
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-    # # ECS
-    # - name: Run ECS tests
-    #   working-directory: ${{github.workspace}}
-    #   shell: bash
-    #   env:
-    #     CC:  gcc-10
-    #     CXX: g++-10
-    #   run: make run_ecs_coverage
+    # ECS
+    - name: Run ECS tests
+      id: ECSTests
+      working-directory: ${{github.workspace}}
+      shell: bash
+      env:
+        CC:  gcc-10
+        CXX: g++-10
+      run: echo "::set-output name=Coverage::$((make run_ecs_coverage && echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' ')) || echo "Failure")"
 
-    # - name: Upload ECS coverage
-    #   working-directory: ${{github.workspace}}
-    #   shell: bash
-    #   env:
-    #     CODECOV_TOKEN: cc222968-8029-42cf-a406-5e81ea5510a4
-    #   run: bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Error while collecting coverage reports"
+    - name: Upload ECS coverage
+      uses: RubbaBoy/BYOB@v1.2.0
+      with:
+        NAME: ECSCoverage
+        LABEL: 'Coverage'
+        STATUS: ${{ steps.ECSTests.outputs.Coverage }}
+        COLOR: blue
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-    # # UI
-    # - name: Run UI tests
-    #   working-directory: ${{github.workspace}}
-    #   shell: bash
-    #   env:
-    #     CC:  gcc-10
-    #     CXX: g++-10
-    #   run: make run_ui_coverage
+    # UI
+    - name: Run UI tests
+      id: UITests
+      working-directory: ${{github.workspace}}
+      shell: bash
+      env:
+        CC:  gcc-10
+        CXX: g++-10
+      run: echo "::set-output name=Coverage::$((make run_ui_coverage && echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' ')) || echo "Failure")"
 
-    # - name: Upload UI coverage
-    #   working-directory: ${{github.workspace}}
-    #   shell: bash
-    #   env:
-    #     CODECOV_TOKEN: 276f7de0-9d3e-42f5-a3ec-0c7d538d2e19
-    #   run: bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Error while collecting coverage reports"
+    - name: Upload UI coverage
+      uses: RubbaBoy/BYOB@v1.2.0
+      with:
+        NAME: UICoverage
+        LABEL: 'Coverage'
+        STATUS: ${{ steps.UITests.outputs.Coverage }}
+        COLOR: blue
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-    # # Widgets
-    # - name: Run Widgets tests
-    #   working-directory: ${{github.workspace}}
-    #   shell: bash
-    #   env:
-    #     CC:  gcc-10
-    #     CXX: g++-10
-    #   run: make run_widgets_coverage
+    # Widgets
+    - name: Run Widgets tests
+      id: WidgetsTests
+      working-directory: ${{github.workspace}}
+      shell: bash
+      env:
+        CC:  gcc-10
+        CXX: g++-10
+      run: echo "::set-output name=Coverage::$((make run_widgets_coverage && echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' ')) || echo "Failure")"
 
-    # - name: Upload Widgets coverage
-    #   working-directory: ${{github.workspace}}
-    #   shell: bash
-    #   env:
-    #     CODECOV_TOKEN: bb177756-4e29-4430-847e-fd77628e0b9c
-    #   run: bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Error while collecting coverage reports"
+    - name: Upload Widgets coverage
+      uses: RubbaBoy/BYOB@v1.2.0
+      with:
+        NAME: WidgetsCoverage
+        LABEL: 'Coverage'
+        STATUS: ${{ steps.WidgetsTests.outputs.Coverage }}
+        COLOR: blue
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-    # # Voxel
-    # - name: Run Voxel tests
-    #   working-directory: ${{github.workspace}}
-    #   shell: bash
-    #   env:
-    #     CC:  gcc-10
-    #     CXX: g++-10
-    #   run: make run_voxel_coverage
+    # Voxel
+    - name: Run Voxel tests
+      id: VoxelTests
+      working-directory: ${{github.workspace}}
+      shell: bash
+      env:
+        CC:  gcc-10
+        CXX: g++-10
+      run: echo "::set-output name=Coverage::$((make run_voxel_coverage && echo $(lcov -l coverage.info | tail -n 1 | cut -f2 -d '|' | awk '{$1=$1;print}' | cut -f1 -d ' ')) || echo "Failure")"
 
-    # - name: Upload Voxel coverage
-    #   working-directory: ${{github.workspace}}
-    #   shell: bash
-    #   env:
-    #     CODECOV_TOKEN: aaff3517-4197-4207-81e5-0e3915f050fc
-    #   run: bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Error while collecting coverage reports"
+    - name: Upload Voxel coverage
+      uses: RubbaBoy/BYOB@v1.2.0
+      with:
+        NAME: VoxelCoverage
+        LABEL: 'Coverage'
+        STATUS: ${{ steps.VoxelTests.outputs.Coverage }}
+        COLOR:  blue
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
